# Generated by Django 2.2.4 on 2019-10-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
